name: 'shaba-games'

x-maven:
  &maven
  tty: true
  user: root
  build:
    context: .
    target: builder
  volumes:
    - ${HOME}/.aws:/home/docker/.aws:ro
    - ${PWD}:/app:cached
    - ${HOME}/.m2:/home/docker/.m2:consistent
  working_dir: /app

services:
  postgres:
    tty: true
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: shaba-games-user-db
      POSTGRES_USER: db
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - "5432:5432"

  migrate:
    tty: true
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/shaba-games-user-db migrate
    volumes:
      - ./src:/flyway/sql
      - .:/flyway/conf
    depends_on:
      - postgres

  jooq-codegen:
    << : *maven
    depends_on:
      - migrate
    environment:
      - MAVEN_TARGET=clean jooq-codegen:generate -P jooq-codegen

  install:
    << : *maven
    environment:
      - MAVEN_TARGET=install -Dmaven.test.skip=true

  spring-boot-app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shaba-games-api
    depends_on:
      - postgres
      - install
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
