name: 'shaba-games'

services:
  migrate:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/shaba-games-user-db migrate
    volumes:
      - ./src:/flyway/sql
      - .:/flyway/conf
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: shaba-games-user-db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: password
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shaba-games-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
